### ISSUE TITLE
[Dev] I know how to use Firestore

### ISSUE THREAD

**Issue by ollyweiss** [ollyweiss/KanJamFam#3]

**Comment by Ahezarkhani** [comment]
Still a WIP, but this is the web course i'm currently building: https://parthean.gitbook.io/web-dev-in-10-days/

Also, here's some firestore quickstarts: 

- This series is good: https://www.youtube.com/watch?v=v_hR4K4auoQ&list=PLl-K7zZEsYLluG5MCVEzXAQ7ACZBCuZgZ
- This quickstart is good: https://firebase.google.com/docs/firestore/quickstart (Use the web tab)
